name:                api-haskell
version:             0.1.0.0
github:              "githubuser/api-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/api-haskell#readme>

dependencies:
- base
- bytestring
- monad-logger
- mtl
- persistent
- persistent-postgresql
- persistent-template
- hedis
- hspec
- servant
- servant-client
- servant-server
- text
- time
- transformers
- aeson
- wai
- warp

library:
  source-dirs: src

executables:
  api-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-haskell

tests:
  api-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-haskell
    - hspec
    - time
